<?php

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

global $NU_FUNC_LOADED__;
if ($NU_FUNC_LOADED__) return;
$NU_FUNC_LOADED__ = true;

/* if our extension has not been loaded, do what we can */
if (!extension_loaded("php_nu_func")) {
  if (!dl("php_nu_func.so")) return;
}



?>
